#!/bin/bash
#
# Usage: VizAln alns.html.gz chrom start [sample]
#           View alignments for an STR in a browser
#           Requires tabix and a bgzipped 
#           file with a corresponding .tbi index

if [ "$#" -eq 3 ] || [ "$#" -eq 4 ]; then
    # Make sure tabix is installed
    hash tabix 2>/dev/null || { echo >&2 "ERROR: VizAln requires tabix. Please check that it's appropriately installed"; exit 1; }

    # Make sure python is installed
    hash python 2>/dev/null || { echo >&2 "ERROR: VizAln requires python. Please check that it's appropriately installed"; exit 1; }

    # Make sure the required python packages are installed
    python -c "import HTMLParser" 2>/dev/null || { echo >&2 "ERROR: VizAln requires the HTMLParser python package. Please check that it's appropriately installed"; exit 1; }

    # Make sure the file exists
    if [ ! -e $1 ]
	then
	cat <<msg
ERROR: Alignment file $1 does not exist
msg
	exit 1
    fi

    # Make sure the file ends in .gz
    if [ ! ${1: -3} == ".gz" ]
    then
	cat <<usage
ERROR: The alignment file must be bgzipped (and end in .gz)
usage
	exit 1
    fi

    # Make sure the tabix index exists
    if [ ! -e $1.tbi ]
	then
	cat<<msg 
ERROR: No .tbi file for alignment file. Index using the following command: 
tabix -p bed $1
msg
	exit 1
    fi

    parent_path=$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )
    chrom=$2
    start=$3
    stop=`expr $start + 100`
    f="/tmp/vizaln.$RANDOM.html"
    if [ "$#" -eq 3 ]
	then
	tabix $1 $chrom:$start-$stop -h | awk -v START=$start '$2 == START || $2 == "#"' | cut -f 1-4 --complement | python ${parent_path}/generate_aln_html.py > $f
    else
	tabix $1 $chrom:$start-$stop -h | awk -v START=$start '$2 == START || $2 == "#"' | awk -v SAMPLE=$4 '$4 == SAMPLE || $4 == "ALL"' | cut -f 1-4 --complement | python ${parent_path}/generate_aln_html.py > $f
    fi

    open $f
else
    cat <<usage
Usage: VizAln alns.html.gz chrom start [sample]
           View alignments for an STR in a browser
           Requires tabix and a bgzipped file with a corresponding .tbi index
usage
fi
